# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oEiLTF6Ca0cDNnzkm0WPjTNZUzbFPjVM
"""

from flask import Flask, jsonify
import pandas as pd

embeddings_df = pd.read_csv('course_embeddings.csv')
app = Flask(__name__)

@app.route('/')
def hello():
    return 'Hello, welcome to your course embeddings API!'

@app.route('/courses', methods=['GET'])
def get_courses():
    courses = []
    for index, row in embeddings_df.iterrows():
        course_data = {
            'name': data['name'][index],
            'embedding': row.tolist()
        }
        courses.append(course_data)
    return jsonify(courses)

if __name__ == '__main__':
    app.run(debug=True)